const MODULE_NAME = '[RETAIN]';

const ActionTypes = {
  GET_RETAIN_USERS_SUCCESS: `${MODULE_NAME} GET_RETAIN_USERS_SUCCESS`,
  GET_FAILED_CAPTURES: `${MODULE_NAME} GET_FAILED_CAPTURES`,
  GET_SUCCESS_CAPTURES: `${MODULE_NAME} GET_SUCCESS_CAPTURES`,
  GET_RETAIN_USERS_SEARCH_SUCCESS: `${MODULE_NAME} GET_RETAIN_USERS_SEARCH_SUCCESS`,
  GET_RETAINED_LIST_SUCCESS: `${MODULE_NAME} GET_RETAINED_LIST_SUCCESS`,
  GET_RETAINED_NOISE_LIST_SUCCESS: `${MODULE_NAME} GET_RETAINED_LIST_SUCCESS`,
  GET_RETAIN_DETAILS_SUCCESS: `${MODULE_NAME} GET_RETAIN_DETAILS_SUCCESS`,
  GET_EMPLOYEE_DETAILS_SUCCESS: `${MODULE_NAME} GET_EMPLOYEE_DETAILS_SUCCESS`,
  GET_EXEMPTED_LIST_SUCCESS: `${MODULE_NAME} GET_EXEMPTED_LIST_SUCCESS`,
  GET_EXEMPTED_USER_SEARCH_SUCCESS: `${MODULE_NAME} GET_EXEMPTED_USER_SEARCH_SUCCESS`,
  RESUME_SUCCESS: `${MODULE_NAME} RESUME_SUCCESS`,
  GET_FAILED_REASON: `${MODULE_NAME} GET_FAILED_REASON`,
};

export default ActionTypes;
