const MODULE_NAME = '[COMMON]';

const ActionTypes = {
  SHOW_LOADING: `${MODULE_NAME} SHOW_LOADING`,
  HIDE_LOADING: `${MODULE_NAME} HIDE_LOADING`,
  SHOW_AUTO_SUGGESTIONS: `${MODULE_NAME} SHOW_AUTO_SUGGESTIONS`,
  RESET_AUTO_SUGGESTIONS: `${MODULE_NAME} RESET_AUTO_SUGGESTIONS`,
  SET_GLOBAL_SEARCH_LIST: `${MODULE_NAME} SET_GLOBAL_SEARCH_LIST`,
  FETCH_DOMAIN_LIST_SUCCESS: `${MODULE_NAME} FETCH_DOMAIN_LIST_SUCCESS`,
  FETCH_CHANNEL_LIST_SUCCESS: `${MODULE_NAME} FETCH_CHANNEL_LIST_SUCCESS`,
};

export default ActionTypes;
